### ISSUE TITLE
image loading in farcaster validator but not in warpcast

### ISSUE THREAD

**Issue by gitkonio** [wevm/frog-archived#157]
### Describe the bug

Hi,

We have a problem where frog generated image is not shown when trying to post frame into warpcast. however image gets renrered when using frame validator.

I suspect that the problem is because og:image is incorrectly set to http://..., and it should be https://... in our case.

It seems that `context.url` is always set to http for some reason. How to force context.url to be correctly set to https, if server is running behind https proxy?

### Frog Version

0.6.4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by jxom** [comment]
Try setting the `origin` property to your proxy URL on the `Frog` instance.

**Comment by gitkonio** [comment]
@jxom  that does not help, og:image url stays http, and I provided https here

```ts
export const app = new Frog({
  origin: 'https://...'
});
```

**Comment by gitkonio** [comment]
@jxom I just tried creating brand new/empty project with bun and node as presets, and even for these projects when I access frame via proxy (https, ngrok) images do not render on the farcaster. however they render in the frame validator tool.

could you please reopen this issue, as it seems to be quite a serious bug?

**Comment by ggomaeng** [comment]
Same issue happening to me - it works in the validator, but not in the post.

It seems like satori image output is svg, which is not supported in warpcast posts.

Here is the [Warpcast Proxy link](https://proxy.wrpcd.net/?url=http%3A%2F%2Fmint.club%2Fframes%2Fbuysell%2Fpreview%2Fnft-base-undefined-member%2Fimage%3Fimage%3DN4IgLghg5iBcIBMCWA3EAaEAHATgeywGc5QwB3OEQsAUywFoBjPAWyzwDsaOwACHGgBsIYVDV4AzQTQAevABb0JAV0GDeZJavVTZTPOqS0WhetQg4%25252BtGWHoAmGYJABfTI3lJBCARzgBtUmhKJBYYTFwCYlhSCngIACNCA2VaXmkJWwAGXjACemyAL3o-TIBdBS01DUqnTEIcRkp5MDAiWAB6dpYkHgA6RkFlePaIQkIaMEJ2iRwIFhop%25252BKherA4wkDIkBDB5SgBGTMyAUgwQeRokKGb9w5O6sABPaRIQPHiAKxpGMAAxI0pmDwID1TgUAJIcBCyOCZVwgCCCMCUJYuNweLw%25252BfylTBIQgAUUIjAgWBoCDgYBwyhorkCMHgyDQ4XwRBe5EoCSSg1SujkihUVU0-J00hk%25252BkMxlMjG4tBwvHeymoSAkDyY0poOFO1CeNBe4Mh0Nge3CEAQyDWABUCPsABx3bAms1QABCeBarEoADYTs44e5PN5uP5aZQGacIizouBYiAeRUhdV4zyxbwjDQTKqeOq5QrRMqMzLeAwDjlZLYAMyOVEgP0YwOwALgILwELrcNRGLsxLJVLpLI5PKFYplOPaBPaTUNJotNqdbp9AZDEZjCZTGZzBbtJYrNanTbbXbwA7HU7nS7XQ%25252B3TWPZ6Rt6fb5-JHwQGQEGYPVQmQwuEIp8gFG%25252BuiAa%25252BPW2IgLiBJEiSZKwBSVI0o2dKIKgYbMu2UaULGqbplKmaytYtiVvc2ovMwgh4Bq8AAMSZNaECZDQACcLiAf6mL1iAey8AAJKcyj6hIPSkl0abxOqpy8AAvLwpwAKx7HYvRlnY1oSbxmDzCwYkamBEGEsSpLkpS1LoMG9IoUykSstGLC2MWWESvmWbyoqea4QWBH0LJjgljY9BkB4tBVjWwH%25252BJxGBmVQWAQL4lkRh28AsKKdi%25252BbYUACNwXmHMFQHsX4IDqSA-FQoJXAICJWnibp%25252BL6dBRnwZgMnVZBBkwXBJmRaGcXoWyiUqilnnpRAKqydlrG1iB%25252BWSSAzW1YZsHGQhkBIV12BodZmEiimjnuc5OZKiqu34aWXk%25252BZ5AWpjlbF1vlsllgA7L0jEACyvRFiGUIQ0WxWtVmRr1IBJfYqX0OlNCZaNmRXRNYWFZp2kzTiNVQfN7Vwk1SMtXVC0NZ1Fm-fFGGJeWkhbZ5ghQCDDxCORmiQ9DoUcQAcuDUJkrNKNtYtHOtfV1I89jaOmR95mMgTPXRhy3biPErq5CwwO9vkpOyBUfheuUgqjthkpqrKLm5odeu8LLOBQjg9B8FgoqySDMiECDQ0qh62XETeoASJwvxzJ4DyUPgsu5Kc0gtOqADK0WMD0SGZL0ezWyxaLXZNeNi22G3wDyDN5SAACKVKKpwhAAPy8AAari-wC6ji3C8tIb4%25252Bn-02aKXGxoNswqs9Y1JzDHEIHgjCEL0c5gP0gzxIj4HI7zOMdSLyFp%25252BtzebdC42M-lFG8AAIgAslPemc3zS1NovqF-QlgOtyrX5uzqkZkRRlBUfdL0QODifVrlN0gAAAsVNBSqGWrlzBqIAZKYE9rKc4ggsAHxnoLWuqdz6EwBlLLk4glbZFyAwbIsYtZVANgdegYlyDgx%25252Blqd2IAPwGgOJgU8Vw-x7FtJ-EKeVkHdQziAAQwhRAoHELGPko4CHijTLrPC2ZXIqlIWQchJsoAkOEIwAA1u0e6UN17sIXqtJul9BE1BvsmHWZhICWEkYbEhExZHcELF5bON0OHiy4e3E6FZahUGvPfUAj9KIgCohIAJrDv6TRAE6AAqgATV4AABQECgJANAKAgOPnXU%25252BOjl56LJidM6J0nZZQ0b3DeIBonSFGOIOJCSyA5HODkWYHBCAQG%25252BEgTg8CsY13gskueJ8VqNwyUTGMW0hFVCTGRbaYj6DcAQOY4hMi5EMFkvYlOC8WwoPQvURo8BmitEIB0LoPQx4LmGKMcYkxpizHmFMUe9ByJQDwNudYe4diUDsM9E8FxGHPNeZgX8lAbl4EWViTGc1QHz3rqLVZzitojIMGM9MkyQaEBYLwZQWASQNDKY7Tu%25252BSAX1kcbo-ptlgYOXGUdHFDYwXgVCBClemcRQTg2WcacOzZz7PHouY5K4znrimAUYk9zdxbCeYeOwbyzxMJFd8xEvy8C3LJZ0oWeK%25252BkAyBm3Olmif7RLwLIgQUz4h%25252B3lUg7RvSL79KznfUiBgn7UT2LJGgHp4j3SCcnMKu9WWHNacC4%25252BBrcZGqXiagGWd1UhJdJCaOvAADCygcD8JifgXIZEPVHy6d6-mQKk0Kt9dSy%25252B6CUgyzlqwZWWCb5q2etbTWNQrwkUjDQr8hpMiYHiI05R6U8DFXDZa3xL834f3oe888z1MAEEaUYP2sBY52B9IUvKKbukNz9agyWXYMEm3zQrbIRazUeKraAGtcA6H-ibS2ttHbn6v2eu-HUvaxVwAHRsQVB4QBljLEpJ9r631vu9EGwF082kgucDOgDabZ5oyAA&s=65af9627cc825b1222c33bd33a29f7d56110582838e96912a42cd1dab3296d63)

Which is [this image](https://mint.club/frames/buysell/preview/nft-base-gami-member/image?image=N4IgLghg5iBcIBMCWA3EAaEAHATgeywGc5QwB3OEQsAUywFoBjPAWyzwDsaOwACHGgBsIYVDV4AzQTQAevABb0JAV0GDeZJavVTZTPOqS0WhetQg4%2BtGWHoAmGYJABfTI3lJBCARzgBtUmhKJBYYTFwCYlhSCngIACNCA2VaXmkJWwAGXjACemyAL3o-TIBdBS01DUqnTEIcRkp5MDAiWAB6dpYkHgA6RkFlePaIQkIaMEJ2iRwIFhop%2BKherA4wkDIkBDB5SgBGTMyAUgwQeRokKGb9w5O6sABPaRIQPHiAKxpGMAAxI0pmDwID1TgUAJIcBCyOCZVwgCCCMCUJYuNweLw%2BfylTBIQgAUUIjAgWBoCDgYBwyhorkCMHgyDQ4XwRBe5EoCSSg1SujkihUVU0-J00hk%2BkMxlMjG4tBwvHeymoSAkDyY0poOFO1CeNBe4Mh0Nge3CEAQyDWABUCPsABx3bAms1QABCeBarEoADYTs44e5PN5uP5aZQGacIizouBYiAeRUhdV4zyxbwjDQTKqeOq5QrRMqMzLeAwDjlZLYAMyOVEgP0YwOwALgILwELrcNRGLsxLJVLpLI5PKFYplOPaBPaTUNJotNqdbp9AZDEZjCZTGZzBbtJYrNanTbbXbwA7HU7nS7XQ%2B3TWPZ6Rt6fb5-JHwQGQEGYPVQmQwuEIp8gFG%2BuiAa%2BPW2IgLiBJEiSZKwBSVI0o2dKIKgYbMu2UaULGqbplKmaytYtiVvc2ovMwgh4Bq8AAMSZNaECZDQACcLiAf6mL1iAey8AAJKcUBzEgXRpvE6qnLwAC8vCnAA7L00l2AA0mJvGYPMLAiRqYEQYSxKkuSlLUugwb0ihTKRKy0YsLYxZYRK%2BZZvKip5rhBYEfQACsjgljY9BkB4tBVjWwH%2BJxGDGVQWAQL4ZkRh28AsKKdjebYUACNwHmHIFQHsX4IAqSA-HdEJ6miVp%2BI6dB%2BnwZgUllZBukwXBhnhaGMXoWy8UqklbmpRAKruZlrG1iBuXiSAdUVXpsEGQhkBIa12BoRZmEiimdkuQ5OZKiqG34aWHleW5fmpllbF1rl1q9HsexKUZiGUIQkXRYt5mRh1IAJfYyX0KlNDpQNmSncNIX5WpGnjTi5VQVNTVwrVkP1ZV03VS1pkvbFGHxeWkirW5ghQN9DxCORmgA0DwUcQAcn9UJkhN0ONTN9MNVV1LM0jsN3XNIZo22y1xF2XLiPErq5CwX29vkOOyBUfheuUgqjthkpqrKjm5jtqu8CLOBQjg9B8Fgorud9MiEN9vUqh6mXETeoASJwvwCYIDyUPgIu5Kc0gtOqADKkWMD0SGZFdRssWiZ0jajjLo%2B10Y8uTOUgAAilSiqcIQAD8vAAGq4v87MwzNXNNshMd829lmilxsY9bMKoACyDRHwMcQgeCMIQvRzmA-SDPEEPgVDLPI8190meXS2Vyt0JDRTuUUbwAAiACyg-aQzrOzaXC0V3FH3V9LX62zqkZkRRlBUdJjENxAf3h9W2XnSAAACyj6hIPR6YXjPVSAUmYAdrKc4ggsDr2HhzYu0dUKvX3hybs4hJbZFyAwbIsZFZVHVttegIlyB-WelqO2IAPwGgOJgU8Vw-x7FtA-IKOVoFtX5iAAQwhRAoHELGPko4MHijTCrPC2YnIqlwWQfB2soA4OEIwAA1u0aSgM570PHmXGBGN3qcJqEfZMyszCQEsIIjWOCJiiO4IWDyidzoMNjkw2u%2B0Ky1CoNeU%2BoBz6URAFRCQnjaFPxGiAJ0ABVAAmrwAACgIFASAaAUB-lvEu81eZT33rYnyh19qWwygolu88QAhOkKMcQ4TIlkByOcHIswOCEAgN8JAnBwGIyLvBGJo9t7xMnrAzGMZVpcKqEmMia0%2BH0G4AgAx2CRFiIYO5CxUdlEtlUeheojR4DNFaIQDoXQei9wXMMUY4xJjTFmPMKYPd6DkSgHgbc6w9w7EoHYBuJ4LiUJuXczAv5KCnLwFMrECNJq-zHtzCecybGrV6QYfp6YhnfUICwXgygsAkgaPki29cMmfPrFYveHSrJfVsgM3aqKGz-PAqEQF094AJzqJOJZ05Vmzg2X3RcOyVz7PXFMAoxILm7i2Ncw8dh7lniobyl5iI3l4DOfippnN0WJMxYfBOijn4hLwKIgQwz4iuwlVA5Ru9pXqJFFeEiZ8DAX2onsdyNAPTxGkt4yOIUV50q2XUn5W8NUoy1Qk9purZ5ZKTi6SEQdeAAGFlA4HYaE-AuQyKOs3s0l1bNvnRslW6tpajozwKFtrUWrApZIKPrLBuRsFY1H1UQkhX5DSZEwPEKp0jUp4HfggANRq3FXxvnfHU5CHnngbpgAgVSjCu1gCHOwPpvXnVjS0nmya46dk5CkYWmbxbZBzeSxxBrQClrgGQ-81ba31sbeRZt19b73w7fyuA3aNhcoPCAMsZZei3ofY%2Bp93p5UjXHe%2B%2BNI9YbjqAA)

--

I'm using latest version of frog and Bun

**Comment by ggomaeng** [comment]
Seems like this could be related? hono-og seems to use svg as default encoding settings if format is not provided.

https://github.com/wevm/hono-og/blob/5cc0ddb25e4f8423276549cde6a4267607e7146c/src/response.ts#L25

**Comment by ggomaeng** [comment]
Can confirm prioritizing png format works.

Before:

```ts
class ImageResponseBase extends Response {
  constructor(element: HonoElement, options: ImageResponseOptions = {}) {
    const { format, headers = {}, status = 200, statusText } = options;

    const body = new ReadableStream({
      async start(controller) {
        await initializeWasm();
        const svg = await elementToSvg(element, options);
        const data =
          format === "png"
            ? await svgToPng(svg, options)
            : new TextEncoder().encode(svg);

        controller.enqueue(data);
        controller.close();
      },
    });

    super(body, {
      headers: {
        "Content-Type": format === "png" ? "image/png" : "image/svg+xml",
        "Cache-Control": options.debug
          ? "no-cache, no-store"
          : "public, immutable, no-transform, max-age=31536000",
        ...headers,
      },
      status,
      statusText,
    });
  }
}
```


After:

```ts
class ImageResponseBase extends Response {
  constructor(element: HonoElement, options: ImageResponseOptions = {}) {
    const { format, headers = {}, status = 200, statusText } = options;

    const body = new ReadableStream({
      async start(controller) {
        await initializeWasm();
        const svg = await elementToSvg(element, options);
        const data =
          format === "svg"
            ? new TextEncoder().encode(svg)
            : await svgToPng(svg, options)

        controller.enqueue(data);
        controller.close();
      },
    });

    super(body, {
      headers: {
        "Content-Type": format === "svg" ? "image/svg+xml":"image/png" ,
        "Cache-Control": options.debug
          ? "no-cache, no-store"
          : "public, immutable, no-transform, max-age=31536000",
        ...headers,
      },
      status,
      statusText,
    });
  }
}
```

**Comment by ggomaeng** [comment]
@gitkonio You could pass "png" format in the imageOptions, but I think "png" format should be the default behavior - it was pretty tough to find this bug since it does not print out any error messages

Edit: On the second thought, I'm not sure if this is the main reason why. `svg` format seems to only problematic for `.transaction` routes. Would this be considered a different issue? @jxom 

https://github.com/wevm/hono-og/pull/33

**Comment by gitkonio** [comment]
@ggomaeng tried imageOptions, but still does not render image in warpcast.

```ts
export const app = new Frog({
  imageOptions: {
    format: 'png',
  }
});
```

or you meant some other imageOptions property? Also above imageOptions requires to set font, at least it gives a ts error for that.

**Comment by ggomaeng** [comment]
> @ggomaeng tried imageOptions, but still does not render image in warpcast.
> 
> ```ts
> export const app = new Frog({
>   imageOptions: {
>     format: 'png',
>   }
> });
> ```
> 
> or you meant some other imageOptions property? Also above imageOptions requires to set font, at least it gives a ts error for that.

Where is your frame being hosted? Are you using proxy like ngrok or cloudflared? 

Could you please share the frame link you tested?

**Comment by gitkonio** [comment]
tested it locally with ngrok proxy in front of the frog server. used https ngrok url

**Comment by 0x330a** [comment]
seem to be having this issue as well

**Comment by 0x330a** [comment]
downgrading dependency solves it for me, none of the other solutions seemed to work

**Comment by jxom** [comment]
Fixed https://github.com/wevm/frog/commit/a6709727d229695517c1bd291e0369e0439572ff

**Comment by gitkonio** [comment]
@jxom still having issues, however now slightly different error. image still does not load in warpcast, loads in frame validator tool.

links to the frame: https://frames.kriptonio.com/frames/simple-gasless-nft-mint

please reopen the issue

**Comment by ggomaeng** [comment]
Could be related. Next.js + frog running with nginx

![image](https://github.com/wevm/frog/assets/18402191/3f6f9824-904a-4594-9e7f-7c3fb572a11d)

**Comment by ggomaeng** [comment]
This also happens in [`getFrameMetadata`](https://frog.fm/platforms/next#bonus-page--frame-co-location)

```ts
export async function generateMetadata(): Promise<Metadata> {
  const frameMetadata = await getFrameMetadata(`${rootUrl}/api/frog`);
  return {
    ...sharedMetadata,
    other: frameMetadata,
  };
}
```

generated metadata:
```html
<meta name="fc:frame" content="vNext"/><meta name="fc:frame:image:aspect_ratio" content="1:1"/><meta name="fc:frame:image" content="http://derivative.art:3000/api/frog/image?image=N4IgLghg5iBcIBMCWA3EAaEAHATgeywGc5QwB3OEAMwBsBTADwAIALAWioFcaamyPuvWozYBjPLyRg6AW0Ji6AO2k4mAK06EwSKgE8FyuqukMwbAMwNeJs2RZS6IAL6ZR9mghxK4AbVLRKJBkYTFwCYlhQQhxRShYwMCJYAHpkhCNUCG0UOgA6CBwwZJo8KDxcrEUQkDIkBDAWOAA2ABZMFjokKHjmlpcQNyQPL0VfAF1MJEIAUUJRCCw6BDgwHE46F38YeGQ0UPwiEnAKeBkzAFZnV3dPb1gfEAARDJQs1DyCsBAJkCnZ%252BcWy1gq3WTh%252BfzmCyWKzWGyAA"/><meta name="og:image" content="http://derivative.art:3000/api/frog/image?image=N4IgLghg5iBcIBMCWA3EAaEAHATgeywGc5QwB3OEAMwBsBTADwAIALAWioFcaamyPuvWozYBjPLyRg6AW0Ji6AO2k4mAK06EwSKgE8FyuqukMwbAMwNeJs2RZS6IAL6ZR9mghxK4AbVLRKJBkYTFwCYlhQQhxRShYwMCJYAHpkhCNUCG0UOgA6CBwwZJo8KDxcrEUQkDIkBDAWOAA2ABZMFjokKHjmlpcQNyQPL0VfAF1MJEIAUUJRCCw6BDgwHE46F38YeGQ0UPwiEnAKeBkzAFZnV3dPb1gfEAARDJQs1DyCsBAJkCnZ%252BcWy1gq3WTh%252BfzmCyWKzWGyAA"/><meta name="og:title" content="Frog Frame"/><meta name="fc:frame:post_url" content="http://derivative.art:3000/api/frog?initialPath=%252Fapi%252Ffrog&amp;amp;previousButtonValues=%2523A_"/><meta name="fc:frame:input:text" content="Enter image url"/><meta name="fc:frame:button:1" content="Create derivative NFTs"/><meta name="fc:frame:button:1:action" content="post"/><meta name="fc:frame:button:1:target" content="https://derivative.art/api/frog/colors?initialPath=%252Fapi%252Ffrog&amp;amp;previousButtonValues=%2523A_"/><meta name="frog:version" content="0.7.16"/>
```

**Comment by gitkonio** [comment]
@jxom please reopen, issue is still present

**Comment by gitkonio** [comment]
works now after frog upgrade to 0.8.0

**Comment by christopherwxyz** [comment]
i think i'm experiencing this same issue: https://github.com/wevm/frog/issues/157#issuecomment-2029365563

Failure from GCP: https://commerce.unofficial.run/api/example/12345

Success from Vercel:
https://commerce-monorepo.vercel.app/api/example/12345

on failure, the validator will return:
```
 {
    "errors": [
        {
            "message": "Frame image error: HTTPError: Response code 500 (Internal Server Error)",
            "reason": "unknown_frame_error"
        }
    ]
}
```
